"use client";

import { useMemo, useState } from "react";
import Image from "next/image";
import { MainHeader } from "@/components/main-header";
import { SiteFooter } from "@/components/site-footer";
import { instagramUrl } from "@/data/nube";

type Pole = "Design" | "Musique" | "Visuel";
type Service = { id: string; name: string; pole: Pole; price: number | null; label: string; internal: boolean };

const services: Service[] = [
  { id: "direction", name: "Direction artistique", pole: "Design", price: 150, label: "dès 150 CHF", internal: true },
  { id: "cover", name: "Cover", pole: "Design", price: 80, label: "dès 80 CHF", internal: true },
  { id: "studio", name: "Studio", pole: "Musique", price: 50, label: "dès 50 CHF/h", internal: true },
  { id: "production", name: "Production", pole: "Musique", price: 150, label: "dès 150 CHF", internal: true },
  { id: "shooting", name: "Shooting", pole: "Visuel", price: 150, label: "dès 150 CHF", internal: true },
  { id: "visualizer", name: "Visualizer", pole: "Visuel", price: 150, label: "dès 150 CHF", internal: true },
  { id: "clip", name: "Clip", pole: "Visuel", price: null, label: "sur devis", internal: false },
  { id: "mix-master", name: "Mix & master", pole: "Musique", price: null, label: "sur devis", internal: false },
];

const poles = [
  { title: "DESIGN", price: "DÈS 80 CHF", items: ["Direction artistique", "Identité visuelle", "Covers", "Affiches", "Supports promotionnels"] },
  { title: "MUSIQUE", price: "DÈS 50 CHF", items: ["Production musicale", "Composition", "Enregistrement studio", "Arrangement", "Accompagnement artistique", "Mix & mastering associé"] },
  { title: "VISUEL", price: "DÈS 80 CHF", items: ["Shooting photo", "Contenu promotionnel", "Contenu vertical", "Visualizer", "Vidéo", "Clip associé"] },
];

const presets = [
  { type: "Single", text: "Construire l’identité complète d’une sortie.", detail: "Direction artistique, cover, studio et shooting", selected: ["direction", "cover", "studio", "shooting"] },
  { type: "EP", text: "Développer un univers cohérent autour de plusieurs morceaux.", detail: "Direction artistique, cover, studio et visualizer", selected: ["direction", "cover", "studio", "visualizer"] },
  { type: "Album", text: "Penser un projet artistique dans sa globalité.", detail: "Une base complète, librement ajustable", selected: ["direction", "cover", "studio", "production", "shooting", "visualizer"] },
];

const section = "relative px-[clamp(24px,7vw,110px)] py-[clamp(72px,9vw,124px)]";
const index = "mb-5 text-[11px] font-black tracking-[.18em] text-[#ff3f98]";
const title = "m-0 text-[clamp(46px,7vw,92px)] leading-[.94] tracking-[-.065em]";

function SectionTitle({ number, children }: { number: string; children: React.ReactNode }) {
  return <div><p className={index}>{number}</p><h2 className={title}>{children}</h2></div>;
}

export function StudioExperience() {
  const [projectType, setProjectType] = useState("Single");
  const [selected, setSelected] = useState<string[]>([]);
  const chosen = services.filter((service) => selected.includes(service.id));
  const totals = useMemo(() => {
    const value = chosen.reduce((sum, service) => sum + (service.price ?? 0), 0);
    const eligible = chosen.filter((service) => service.internal && service.price !== null);
    const discount = eligible.length >= 3 ? Math.round(eligible.reduce((sum, service) => sum + (service.price ?? 0), 0) * 0.15) : 0;
    return { value, discount, estimate: value - discount, quote: chosen.some((service) => service.price === null) };
  }, [chosen]);

  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const choosePreset = (preset: (typeof presets)[number]) => {
    setProjectType(preset.type);
    setSelected(preset.selected);
    window.setTimeout(() => document.querySelector("#configurateur")?.scrollIntoView({ behavior: "smooth" }), 20);
  };

  return <main className="bg-[#09090b] text-[#f1efe9]">
    <MainHeader />

    <section id="top" className="relative flex min-h-[740px] items-center overflow-hidden bg-[radial-gradient(circle_at_78%_42%,rgba(255,63,152,.2),transparent_30%),#09090b] px-[clamp(24px,7vw,110px)] pb-20 pt-36 min-[901px]:min-h-[90svh]">
      <div className="relative z-10 max-w-[900px]"><p className={index}>ACTIVITÉ CRÉATIVE PERMANENTE DE NUBE</p><h1 className="m-0 text-[clamp(70px,12vw,164px)] leading-[.8] tracking-[-.085em]">NUBE<br /><em className="ml-[clamp(16px,7vw,100px)] font-[Georgia] font-normal text-transparent [-webkit-text-stroke:1.5px_rgba(241,239,233,.82)]">STUDIO</em></h1><p className="ml-[clamp(16px,7vw,100px)] mt-12 max-w-xl text-[clamp(18px,2vw,26px)] leading-[1.4]">Incubateur de projets artistiques indépendants.</p><p className="ml-[clamp(16px,7vw,100px)] mt-5 text-[12px] font-black tracking-[.18em] text-white/65">DESIGN · MUSIQUE · VISUEL</p><div className="ml-[clamp(16px,7vw,100px)] mt-9 flex flex-wrap gap-5"><a className="bg-[#f1efe9] px-6 py-5 text-[12px] font-black tracking-[.13em] text-[#09090b] hover:bg-[#ff3f98]" href="#configurateur">CONSTRUIRE MON PROJET</a><a className="border-b border-white/40 py-4 text-[11px] font-black tracking-[.14em]" href="#poles">DÉCOUVRIR LE STUDIO</a></div></div>
      <div className="absolute right-[3vw] top-[35%] aspect-square w-[min(62vw,430px)] rounded-full border border-white/10 opacity-45 before:absolute before:inset-[17%] before:rounded-full before:border before:border-white/10 after:absolute after:inset-[35%] after:rounded-full after:bg-[#ff3f98]/15 after:blur-xl min-[901px]:right-[5vw] min-[901px]:top-[22%] min-[901px]:w-[min(43vw,630px)]" aria-hidden="true" />
      <div data-studio-cloud className="absolute right-[4vw] top-[48%] z-[2] grid aspect-square w-[min(58vw,320px)] animate-[studioCloudFloat_7s_ease-in-out_infinite] place-items-center opacity-40 motion-reduce:animate-none min-[901px]:right-[9vw] min-[901px]:top-[28%] min-[901px]:w-[min(28vw,410px)] min-[901px]:opacity-75" aria-hidden="true"><Image className="object-contain p-[11%] drop-shadow-[0_0_35px_rgba(255,63,152,.42)]" src="/nube-logo.png" alt="" fill sizes="(min-width: 901px) 28vw, 58vw" /><span className="absolute right-0 top-1/2 origin-center rotate-90 text-[10px] font-black tracking-[.2em] text-[#c8c2cb]">NUBE STUDIO · LAUSANNE</span></div>
    </section>

    <section id="poles" className={`${section} bg-[#f1efe9] text-[#09090b]`}><div className="grid gap-8 min-[901px]:grid-cols-[1.15fr_.85fr] min-[901px]:items-end"><SectionTitle number="01 / LES TROIS PÔLES">UNE IDÉE.<br /><em className="font-[Georgia] font-normal text-[#ff3f98]">PLUSIEURS FORMES.</em></SectionTitle><p className="max-w-lg text-[15px] leading-[1.7] text-[#555159]">NUBE Studio réunit les compétences nécessaires pour accompagner un projet de son intention jusqu’à sa réalisation.</p></div><div className="mt-16 grid border-t border-[#bbb6ae] min-[901px]:grid-cols-3">{poles.map((pole, poleIndex) => <article className="flex min-h-[430px] flex-col border-b border-[#bbb6ae] py-8 min-[901px]:border-b-0 min-[901px]:border-r min-[901px]:px-8 min-[901px]:first:pl-0 min-[901px]:last:border-r-0" key={pole.title}><div className="flex justify-between text-[11px] font-black tracking-[.13em]"><span className="font-[Georgia] text-base italic text-[#ff3f98]">0{poleIndex + 1}</span><span>{pole.price}</span></div><h3 className="mb-7 mt-14 text-[clamp(40px,4vw,60px)] tracking-[-.06em]">{pole.title}</h3><ul className="m-0 list-none p-0">{pole.items.map((item) => <li className="border-b border-[#d0cbc3] py-2.5 text-[13px] text-[#4f4b52]" key={item}>{item}</li>)}</ul><a className="mt-auto pt-7 text-[11px] font-black tracking-[.13em]" href="#carte">VOIR LES PRESTATIONS</a></article>)}</div><p className="mt-5 text-[11px] leading-[1.6] text-[#6b666e]">Tarifs de départ indicatifs. Chaque projet fait l’objet d’une proposition adaptée.</p></section>

    <section id="carte" className={`${section} bg-[#0c0b0e]`}><div className="grid gap-8 min-[901px]:grid-cols-[1.15fr_.85fr]"><SectionTitle number="02 / À LA CARTE">JUSTE CE DONT<br /><em className="font-[Georgia] font-normal text-[#ff3f98]">TU AS BESOIN.</em></SectionTitle><p className="max-w-lg text-[15px] leading-[1.7] text-white/70">Chaque prestation peut être choisie indépendamment. Sélectionne celles qui correspondent à ton projet.</p></div><div className="mt-16 border-t border-white/15">{services.map((service, serviceIndex) => { const active = selected.includes(service.id); return <button type="button" className={`grid min-h-24 w-full grid-cols-[36px_1fr_34px] items-center gap-3 border-0 border-b border-white/15 bg-transparent text-left text-white transition min-[701px]:grid-cols-[48px_1fr_.55fr_.4fr_34px] ${active ? "bg-[#ff3f98]/10" : "hover:bg-white/[.03]"}`} key={service.id} onClick={() => toggle(service.id)} aria-pressed={active}><span className="font-[Georgia] text-sm italic text-[#ff3f98]">{String(serviceIndex + 1).padStart(2, "0")}</span><span className="text-[clamp(21px,2.3vw,34px)] font-black tracking-[-.04em]">{service.name}</span><span className="hidden text-[11px] font-black uppercase tracking-[.13em] text-white/55 min-[701px]:block">{service.pole}{!service.internal && " · ASSOCIÉ"}</span><strong className="col-start-2 text-[11px] uppercase tracking-[.1em] min-[701px]:col-auto">{service.label}</strong><i className={`col-start-3 row-start-1 grid h-8 w-8 place-items-center rounded-full border not-italic ${active ? "border-[#ff3f98] bg-[#ff3f98] text-black" : "border-white/30 text-[#ff3f98]"}`}>{active ? "×" : "+"}</i></button>; })}</div></section>

    <section id="configurateur" className={`${section} scroll-mt-24 bg-[#f1efe9] text-[#09090b]`}><SectionTitle number="03 / CONSTRUIRE MON PROJET">TON PROJET.<br /><em className="font-[Georgia] font-normal text-[#ff3f98]">À TA MANIÈRE.</em></SectionTitle><p className="mt-7 max-w-xl text-[15px] leading-[1.7] text-[#555159]">Sélectionne une base, ajoute ce dont tu as besoin et retire le reste. Rien n’est figé.</p><div className="mt-16 grid items-start gap-12 min-[901px]:grid-cols-[1.2fr_.8fr]">
      <div><fieldset className="mb-14 border-0 p-0"><legend className="mb-6 w-full border-b border-[#bbb6ae] pb-4 text-[11px] font-black tracking-[.13em]"><span className="mr-4 font-[Georgia] italic text-[#ff3f98]">01</span>QU’EST-CE QUE TU CRÉES ?</legend><div className="grid gap-2 min-[581px]:grid-cols-2">{["Single", "EP", "Album", "Identité artistique", "Autre"].map((type) => <button type="button" className={`flex min-h-14 items-center justify-between border px-4 text-[13px] font-bold ${projectType === type ? "border-[#ff3f98] bg-[#ff3f98]" : "border-[#c4bfb7] bg-transparent"} ${type === "Autre" ? "min-[581px]:col-span-2" : ""}`} key={type} onClick={() => setProjectType(type)} aria-pressed={projectType === type}>{type}<span>{projectType === type ? "●" : "○"}</span></button>)}</div></fieldset>
      <fieldset className="border-0 p-0"><legend className="mb-6 w-full border-b border-[#bbb6ae] pb-4 text-[11px] font-black tracking-[.13em]"><span className="mr-4 font-[Georgia] italic text-[#ff3f98]">02</span>DE QUOI AS-TU BESOIN ?</legend><div className="grid gap-8">{(["Design", "Musique", "Visuel"] as Pole[]).map((pole) => <div key={pole}><h3 className="mb-2 text-[11px] tracking-[.15em] text-[#ff3f98]">{pole.toUpperCase()}</h3>{services.filter((service) => service.pole === pole).map((service) => { const active = selected.includes(service.id); return <label className={`grid min-h-16 cursor-pointer grid-cols-[34px_1fr] items-center gap-3 border-b border-[#c9c4bc] px-2 py-3 ${active ? "bg-[#ff3f98]/10" : ""}`} key={service.id}><input className="sr-only" type="checkbox" checked={active} onChange={() => toggle(service.id)} /><span className={`grid h-7 w-7 place-items-center rounded-full border ${active ? "border-[#ff3f98] bg-[#ff3f98]" : "border-[#aaa4ac] text-[#ff3f98]"}`}>{active ? "×" : "+"}</span><span className="flex flex-col justify-between gap-1 min-[581px]:flex-row min-[581px]:items-baseline"><strong className="text-[14px]">{service.name}</strong><small className="text-[11px] uppercase tracking-[.08em] text-[#6a656d]">{service.label}{!service.internal && " · associé"}</small></span></label>; })}</div>)}</div></fieldset></div>
      <aside className="sticky top-28 overflow-hidden bg-[#0b0a0d] p-6 text-[#f1efe9] shadow-[0_25px_70px_rgba(15,8,12,.17)]" aria-live="polite"><div className="mb-6 border-b border-white/15 pb-4"><p className="m-0 text-[11px] font-black tracking-[.15em] text-[#ff3f98]">TON PROJET</p><span className="mt-2 block text-[11px] text-white/55">{selected.length} SÉLECTION{selected.length !== 1 ? "S" : ""}</span></div><h3 className="my-6 text-[clamp(36px,4vw,58px)] leading-none tracking-[-.06em]">{projectType}</h3><div className="min-h-28 border-b border-white/15 pb-5">{chosen.length === 0 ? <p className="max-w-xs text-[13px] leading-[1.6] text-white/55">Sélectionne tes premières prestations pour construire ton parcours.</p> : chosen.map((service) => <div className="flex min-h-8 items-center justify-between text-[13px] text-white/80" key={service.id}><span>{service.name}</span><button className="border-0 bg-transparent text-lg text-white/55" type="button" onClick={() => toggle(service.id)} aria-label={`Retirer ${service.name}`}>×</button></div>)}</div><div className="border-b border-white/15 py-5 text-[12px]"><div className="mb-2 flex justify-between text-white/65"><span>Valeur</span><strong>{totals.value} CHF{totals.quote ? " + devis" : ""}</strong></div><div className="flex justify-between"><span>Réduction parcours</span><strong className={totals.discount ? "text-[#ff3f98]" : "text-white/55"}>{totals.discount ? `− ${totals.discount} CHF` : "—"}</strong></div><p className="mb-0 mt-4 text-[11px] leading-[1.5] text-white/55">Trois prestations internes activent une réduction de 15 %.</p></div><div className="flex items-end justify-between gap-4 py-6"><span className="text-[11px] font-black tracking-[.14em] text-white/60">ESTIMATION</span><strong className="text-[clamp(30px,3vw,42px)] tracking-[-.05em] text-[#ff3f98]">{totals.estimate} CHF{totals.quote ? "*" : ""}</strong></div><a className="block bg-[#ff3f98] px-5 py-5 text-center text-[12px] font-black tracking-[.13em] text-[#09090b]" href={instagramUrl} target="_blank" rel="noreferrer">PARLER DU PROJET SUR INSTAGRAM</a><p className="mb-0 mt-4 text-[11px] leading-[1.5] text-white/50">Estimation indicative. Le tarif définitif est établi après échange.</p></aside>
    </div></section>

    <section id="parcours" className={`${section} bg-[#0c0b0e]`}><div className="grid gap-8 min-[901px]:grid-cols-[1.15fr_.85fr]"><SectionTitle number="04 / PARCOURS">UN POINT<br /><em className="font-[Georgia] font-normal text-[#ff3f98]">DE DÉPART.</em></SectionTitle><p className="max-w-lg text-[15px] leading-[1.7] text-white/70">Ces parcours ne sont pas des packs. Ils préremplissent le configurateur et restent modifiables.</p></div><div className="mt-16 grid border-t border-white/15 min-[901px]:grid-cols-3">{presets.map((preset, presetIndex) => <article className="flex min-h-[360px] flex-col border-b border-white/15 py-8 min-[901px]:border-b-0 min-[901px]:border-r min-[901px]:px-8 min-[901px]:first:pl-0 min-[901px]:last:border-r-0" key={preset.type}><span className="font-[Georgia] italic text-[#ff3f98]">0{presetIndex + 1}</span><h3 className="mb-5 mt-12 text-[clamp(42px,5vw,66px)] tracking-[-.06em]">{preset.type.toUpperCase()}</h3><p className="max-w-xs text-[14px] leading-[1.6] text-white/70">{preset.text}</p><small className="mt-3 text-[11px] uppercase leading-[1.5] tracking-[.08em] text-white/45">{preset.detail}</small><button className="mt-auto border-0 border-t border-white/15 bg-transparent pt-5 text-left text-[11px] font-black tracking-[.13em] text-white" type="button" onClick={() => choosePreset(preset)}>PERSONNALISER</button></article>)}</div></section>

    <section id="incubation" className={`${section} overflow-hidden bg-[radial-gradient(circle_at_80%_50%,rgba(255,63,152,.2),transparent_28%),#100b10]`}><div className="grid items-center gap-14 min-[901px]:grid-cols-[1.1fr_.9fr]"><div><SectionTitle number="05 / ACCOMPAGNEMENT LONG TERME">INCUBATED BY<br /><em className="font-[Georgia] font-normal text-[#ff3f98]">NUBE STUDIO</em></SectionTitle><p className="mt-9 text-xl">Certains projets dépassent la prestation.</p><p className="max-w-xl text-[15px] leading-[1.7] text-white/70">Les projets accompagnés dans leur développement artistique global peuvent intégrer le programme d’incubation.</p><strong className="mt-7 block text-[13px]">Direction artistique. Musique. Image. Une même vision.</strong></div><div className="mx-auto grid aspect-square w-[min(70vw,390px)] place-items-center rounded-full border border-dashed border-white/30 text-center"><div><Image className="mx-auto w-1/2 opacity-75" src="/nube-logo.png" alt="" width={300} height={300} /><strong className="block text-[clamp(30px,4vw,48px)] tracking-[-.05em] text-[#ff3f98]">INCUBATED</strong><span className="text-[11px] font-black tracking-[.18em]">BY NUBE STUDIO</span></div></div></div><p className="mt-16 border-t border-white/15 pt-5 text-[11px] text-white/50">L’incubation est un statut attribué aux projets réellement accompagnés en profondeur.</p></section>

    <section id="structure" className={`${section} bg-[#f1efe9] text-[#09090b]`}><SectionTitle number="06 / L’ÉCOSYSTÈME">DES RÔLES CLAIRS.<br /><em className="font-[Georgia] font-normal text-[#ff3f98]">UNE VISION COMMUNE.</em></SectionTitle><div className="mt-16 grid border-t border-[#bbb6ae] min-[901px]:grid-cols-3">{[{ label: "CLOUDS FONDATEURS", name: "NEL · ITONA · TENGSHE · G2L · Bx", text: "Ils construisent la structure NUBE et sa vision dans le temps." }, { label: "COLLABORATEURS ASSOCIÉS", name: "EXPERTISES PONCTUELLES", text: "Ils interviennent sur certaines spécialités comme le mix/mastering et les clips." }, { label: "PROJETS INCUBÉS", name: "ACCOMPAGNÉS EN PROFONDEUR", text: "Ils développent leur univers artistique avec NUBE Studio." }].map((item, itemIndex) => <article className="min-h-[290px] border-b border-[#bbb6ae] py-8 min-[901px]:border-b-0 min-[901px]:border-r min-[901px]:px-8 min-[901px]:first:pl-0 min-[901px]:last:border-r-0" key={item.label}><span className="font-[Georgia] italic text-[#ff3f98]">0{itemIndex + 1}</span><p className="mb-4 mt-12 text-[11px] font-black tracking-[.13em] text-[#6b666e]">{item.label}</p><h3 className="text-[clamp(24px,2.7vw,38px)] leading-[1.05] tracking-[-.045em]">{item.name}</h3><p className="text-[13px] leading-[1.7] text-[#555159]">{item.text}</p></article>)}</div></section>

    <section id="contact" className="relative flex min-h-[600px] flex-col items-center justify-center bg-[#ff3f98] px-6 pb-36 pt-24 text-center text-[#09090b]"><p className="mb-5 text-[11px] font-black tracking-[.18em]">PREMIER ÉCHANGE</p><h2 className={title}>ON CONSTRUIT<br /><em className="font-[Georgia] font-normal text-white">QUOI ENSEMBLE ?</em></h2><p className="my-8 max-w-xl text-[15px] leading-[1.7]">Une prestation précise ou un projet encore flou : commence par nous raconter où tu veux aller.</p><a className="bg-[#09090b] px-7 py-5 text-[12px] font-black tracking-[.13em] text-white" href={instagramUrl} target="_blank" rel="noreferrer">NOUS ÉCRIRE SUR INSTAGRAM</a><SiteFooter tagline="CONTINUER À CRÉER" copyright="NUBE STUDIO" darkBorder links={[{ href: "/", label: "NUBE" }, { href: "/festival", label: "FESTIVAL" }, { href: "/infos", label: "INFOS" }]} /></section>
  </main>;
}
