import type { Metadata } from "next";

/* eslint-disable @next/next/no-html-link-for-pages */

export const metadata: Metadata = {
  title: "NUBE Studio — Création & direction artistique",
  description: "Le pôle création de NUBE : direction artistique, image, contenu et expérience scénique pour les artistes et projets culturels.",
};

const services = [
  { number: "01", title: "Direction artistique", text: "On transforme une intention en univers cohérent : concept, références, palette, typographies et langage visuel.", tags: ["IDENTITÉ", "MOODBOARD", "STRATÉGIE"] },
  { number: "02", title: "Image & contenu", text: "Covers, campagnes, formats sociaux et contenus vidéo pensés pour raconter le projet — pas seulement le décorer.", tags: ["COVERS", "PHOTO", "VIDÉO"] },
  { number: "03", title: "Expérience scénique", text: "De l’annonce au live : une continuité visuelle qui donne au public une vraie expérience avant, pendant et après la scène.", tags: ["LIVE", "SCÉNOGRAPHIE", "PROMOTION"] },
];

const section = "relative px-[clamp(24px,7vw,110px)] py-[clamp(90px,11vw,170px)]";
const index = "mb-[38px] text-[9px] font-black tracking-[.25em] opacity-55";

function Header() {
  return (
    <header className="absolute inset-x-0 top-0 z-20 grid h-[78px] grid-cols-[1fr_auto] items-center border-b border-white/15 px-[clamp(24px,4vw,72px)] min-[901px]:h-24 min-[901px]:grid-cols-[1fr_auto_1fr]">
      <a className="group flex items-center gap-[11px] text-xl font-black tracking-[-1.5px] min-[581px]:text-2xl" href="/" aria-label="Retour au festival NUBE"><img className="h-[34px] w-[34px] object-contain drop-shadow-[0_0_9px_rgba(255,63,152,.42)] transition group-hover:-rotate-6 group-hover:scale-105 min-[581px]:h-[42px] min-[581px]:w-[42px]" src="/nube-logo.png" alt="" /><span>NUBE<sup className="ml-0.5 align-top text-[8px]">®</sup></span></a>
      <nav className="hidden gap-[38px] min-[901px]:flex" aria-label="Navigation création">{[['/','FESTIVAL'],['#services','SERVICES'],['#projets','PROJETS'],['#contact','CONTACT']].map(([href,label]) => <a className="text-[11px] font-extrabold tracking-[.14em] opacity-70 transition hover:text-[#ff3f98] hover:opacity-100" href={href} key={href}>{label}</a>)}</nav>
      <a className="flex items-center gap-2 justify-self-end text-[8px] font-extrabold tracking-[.14em] min-[581px]:gap-3.5 min-[581px]:text-[11px]" href="/">RETOUR AU FESTIVAL <span className="text-base text-[#ff3f98]">↖</span></a>
    </header>
  );
}

function Cloud() {
  const orb = "absolute rounded-full bg-[radial-gradient(circle_at_35%_28%,#ffa9d1_0,#ff4aa0_25%,#a52479_60%,#27122f_100%)] shadow-[inset_-25px_-30px_60px_rgba(0,0,0,.5),0_0_50px_rgba(255,42,145,.15)]";
  return <div className="absolute right-[-23vw] top-[55%] z-2 aspect-square w-[75vw] opacity-75 saturate-110 min-[581px]:right-[-8vw] min-[581px]:top-[48%] min-[581px]:w-[65vw] min-[901px]:right-[clamp(-110px,-2vw,-25px)] min-[901px]:top-[18%] min-[901px]:w-[min(43vw,650px)] min-[901px]:opacity-100" aria-hidden="true"><div className="absolute inset-[13%] rounded-full bg-[#ff3f98] opacity-30 blur-[80px] motion-safe:animate-pulse" /><div className={`${orb} left-[8%] top-[28%] h-1/2 w-1/2`} /><div className={`${orb} right-[3%] top-[21%] h-[58%] w-[58%]`} /><div className={`${orb} left-[31%] top-[2%] h-[42%] w-[42%]`} /><div className={`${orb} bottom-[15%] left-[24%] h-[43%] w-[55%]`} /><div className="absolute inset-[28%] grid place-items-center rounded-full border border-white/35 font-[Georgia] text-[clamp(70px,10vw,165px)] italic text-white mix-blend-overlay drop-shadow-[0_0_25px_white]">N</div><span className="absolute right-[4%] top-[48%] rotate-90 text-[8px] font-black tracking-[.28em] text-white/70">CONTINUER À CRÉER</span><span className="absolute bottom-[22%] left-[5%] -rotate-12 text-[8px] font-black tracking-[.28em] text-white/70">NUBE STUDIO</span></div>;
}

export default function CreationPage() {
  return (
    <main>
      <Header />
      <section id="top" className="relative flex min-h-[780px] items-start overflow-hidden bg-[radial-gradient(circle_at_70%_50%,rgba(117,71,180,.2),transparent_38%),#09090b] px-[clamp(24px,7vw,110px)] pb-[90px] pt-[145px] min-[581px]:min-h-[860px] min-[581px]:pt-[170px] min-[901px]:min-h-[94svh] min-[901px]:items-center min-[901px]:pt-[150px]">
        <div className="absolute left-[clamp(24px,7vw,110px)] top-[108px] text-[10px] font-extrabold tracking-[.23em] text-[#aaa5ad] min-[581px]:top-[130px]"><span className="mr-2 inline-block h-1.5 w-1.5 rounded-full bg-[#ff3f98] shadow-[0_0_12px_#ff3f98]" /> LE PÔLE CRÉATION DE NUBE</div>
        <div className="relative z-4 mt-[35px] w-full min-[901px]:w-[64%]"><p className="mb-[18px] text-[clamp(10px,.9vw,13px)] font-extrabold tracking-[.31em] text-[#aca8af]">POUR LES ARTISTES QUI VEULENT</p><h1 className="m-0 text-[clamp(53px,13vw,100px)] leading-[.84] font-[950] tracking-[-.075em] min-[901px]:text-[clamp(62px,8.5vw,145px)] min-[901px]:leading-[.78]"><span className="block whitespace-nowrap">CONSTRUIRE</span><span className="block whitespace-nowrap text-transparent [-webkit-text-stroke:1.5px_rgba(241,239,233,.78)] min-[901px]:ml-[clamp(20px,7vw,120px)]">UN UNIVERS</span></h1><p className="mt-[30px] max-w-[310px] text-[13px] leading-[1.7] text-[#bdb8c1] min-[581px]:mt-[42px] min-[581px]:max-w-[510px] min-[581px]:text-[clamp(14px,1.1vw,17px)] min-[901px]:ml-[clamp(8px,8vw,130px)]">Direction artistique, image et expériences.<br />On donne une forme forte aux idées qui méritent d’exister.</p><div className="mt-8 flex flex-col items-start gap-[22px] min-[581px]:flex-row min-[581px]:items-center min-[581px]:gap-[34px] min-[901px]:ml-[clamp(8px,8vw,130px)]"><a className="inline-flex items-center gap-[30px] bg-[#f1efe9] px-[21px] py-[17px] text-[10px] font-black tracking-[.13em] text-[#08080a] transition hover:-translate-y-0.5 hover:bg-[#ff3f98]" href="#contact">DÉMARRER UN PROJET <span className="text-base">↗</span></a><a className="border-b border-[#666] pb-1.5 text-[9px] font-extrabold tracking-[.17em]" href="#services">VOIR LES SERVICES <span className="ml-2 text-[#ff3f98]">↓</span></a></div></div>
        <Cloud /><div className="absolute bottom-[35px] right-[4vw] z-5 text-[9px] tracking-[.2em] text-[#706c73]">STUDIO — 2026</div>
      </section>

      <section id="services" className={`${section} bg-[#f1efe9] text-[#0a0a0d]`}>
        <div className="grid items-end gap-[60px] min-[901px]:grid-cols-[1.2fr_.8fr]"><div><p className={index}>01 / CE QU’ON FAIT</p><h2 className="m-0 text-[49px] leading-[.85] font-[950] tracking-[-.065em] min-[581px]:text-[clamp(50px,7vw,105px)]">UNE IDÉE.<br /><em className="font-[Georgia] font-normal text-[#ff3f98]">TOUT UN MONDE.</em></h2></div><p className="mt-[30px] mb-[5px] max-w-[450px] text-[17px] leading-[1.65] text-[#55525a] min-[901px]:mt-0">NUBE Studio aide les artistes et projets culturels à créer une identité qu’on reconnaît, qu’on ressent et qu’on retient.</p></div>
        <div className="mt-[55px] border-t border-[#b9b5ae] min-[581px]:mt-[90px]">{services.map((service) => <article className="relative grid min-h-[148px] grid-cols-[24px_1fr_22px] items-center gap-3.5 border-b border-[#b9b5ae] py-7 transition hover:bg-[#ff3f98]/5 min-[581px]:grid-cols-[35px_1fr_30px] min-[901px]:grid-cols-[50px_1.15fr_1.2fr_.85fr_30px] min-[901px]:gap-[30px] min-[901px]:py-0 min-[901px]:hover:pl-[15px]" key={service.number}><span className="font-[Georgia] text-sm italic text-[#ff3f98]">{service.number}</span><h3 className="m-0 text-[26px] tracking-[-.045em] min-[581px]:text-[clamp(24px,2.5vw,38px)]">{service.title}</h3><p className="col-start-2 m-0 max-w-[390px] text-[13px] leading-[1.65] text-[#605d64] min-[901px]:col-auto">{service.text}</p><div className="col-start-2 flex flex-wrap gap-1.5 min-[901px]:col-auto">{service.tags.map(tag => <span className="rounded-full border border-[#b8b3ab] px-[9px] py-[7px] text-[7px] font-black tracking-[.11em]" key={tag}>{tag}</span>)}</div><span className="col-start-3 row-start-1 text-xl text-[#ff3f98] min-[901px]:col-auto">↗</span></article>)}</div>
      </section>

      <section id="projets" className={`${section} overflow-hidden bg-[#09090b] before:absolute before:right-[-30vw] before:top-[20%] before:h-[50vw] before:w-[50vw] before:rounded-full before:bg-[#662ec6] before:opacity-15 before:blur-[130px]`}>
        <div className="relative z-2 mb-[85px] grid gap-8 min-[901px]:grid-cols-[.55fr_1.45fr]"><p className={index}>02 / PROJET FONDATEUR</p><p className="m-0 text-[34px] leading-[.98] font-black tracking-[-.055em] min-[581px]:text-[clamp(34px,5.1vw,78px)]">LE FESTIVAL EST AUSSI<br /><span className="text-transparent [-webkit-text-stroke:1px_rgba(255,255,255,.8)]">NOTRE LABORATOIRE.</span><br /><em className="font-[Georgia] font-normal text-[#ff3f98]">ON TESTE EN VRAI.</em></p></div>
        <div className="relative z-2 grid items-center gap-[45px] min-[901px]:grid-cols-[1.2fr_.8fr] min-[901px]:gap-[clamp(45px,7vw,110px)]"><div className="relative aspect-[1.04] overflow-hidden border border-white/15 bg-[linear-gradient(145deg,#171219,#291022_70%,#0d0b0f)]"><div className="absolute inset-0 origin-bottom [transform:perspective(600px)_rotateX(55deg)_scale(1.7)] bg-[linear-gradient(rgba(255,255,255,.15)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.15)_1px,transparent_1px)] bg-[size:42px_42px] opacity-25" /><div className="absolute right-[9%] top-[7%] aspect-square w-[54%] rounded-full bg-[radial-gradient(circle_at_35%_30%,#ffe0ef,#ff3f98_38%,#70194d_72%)] shadow-[0_0_70px_#ff3f9866]" /><div className="absolute bottom-[14%] left-[5%] scale-y-[1.45] text-[clamp(68px,10vw,158px)] leading-[.75] font-[950] tracking-[-.085em] text-[#f1efe9] mix-blend-difference">NUBE</div><div className="absolute right-[5%] bottom-[5%] text-right text-[8px] leading-[1.55] font-black tracking-[.22em] text-white">DA / CAMPAGNE<br />CONTENU / SCÈNE</div></div><div className="max-w-[620px]"><p className="mb-[18px] text-[8px] font-black tracking-[.2em] text-[#8f8993]">ÉVÉNEMENT · DIRECTION ARTISTIQUE</p><h2 className="m-0 text-[64px] leading-[.8] tracking-[-.075em] min-[581px]:text-[clamp(60px,7vw,108px)]">NUBE<br />OPEN AIR</h2><span className="mt-[25px] block text-[8px] font-black tracking-[.18em] text-[#ff3f98]">IDENTITÉ / CAMPAGNE / EXPÉRIENCE</span><a className="mt-[55px] inline-flex items-center gap-[18px] border-b border-[#555] pb-2 text-[9px] font-black tracking-[.15em]" href="/">VOIR LE FESTIVAL <i className="text-lg not-italic text-[#ff3f98]">↗</i></a></div></div>
      </section>

      <section id="contact" className={`${section} relative flex min-h-[760px] flex-col items-center justify-start overflow-hidden bg-[#ff3f98] pt-[115px] text-center text-[#0b0a0d] before:absolute before:inset-0 before:bg-[radial-gradient(circle_at_20%_20%,#fff,transparent_23%)] before:opacity-20 min-[581px]:min-h-[92vh] min-[581px]:justify-center`}>
        <div className="absolute right-[-4vw] top-[-8vw] grid aspect-square w-[30vw] place-items-center rounded-full border border-black/15 text-[10vw] opacity-20" aria-hidden="true">☁</div><p className={`${index} relative !mb-[30px] opacity-70`}>03 / ON CRÉE QUOI ?</p><h2 className="relative m-0 text-[49px] leading-[.85] font-[950] tracking-[-.065em] min-[581px]:text-[clamp(50px,7vw,105px)]">TON PROJET<br /><em className="font-[Georgia] font-normal text-[#fff4f8] drop-shadow-[0_0_35px_rgba(255,255,255,.35)]">MÉRITE SON UNIVERS.</em></h2><p className="relative mx-auto my-8 max-w-[540px] text-[13px] leading-[1.65] min-[581px]:text-[15px]">Artiste, collectif, lieu ou projet culturel : raconte-nous où tu veux aller. On réfléchit à la suite avec toi.</p><a className="relative mt-[15px] flex w-[min(510px,100%)] items-center justify-between bg-[#09090b] py-[11px] pr-3 pl-[25px] text-left text-[10px] font-black tracking-[.15em] text-white transition hover:-translate-y-1 hover:shadow-[0_14px_30px_rgba(30,0,15,.25)]" href="mailto:contact@nube.studio?subject=Parlons%20de%20mon%20projet"><span>PARLER DE MON PROJET</span><i className="grid h-[49px] w-[49px] place-items-center bg-white text-[22px] not-italic text-black">↗</i></a><p className="relative mt-3 text-[8px] tracking-[.12em] opacity-60">Adresse de contact provisoire — à remplacer par ton e-mail</p>
        <footer className="absolute inset-x-[clamp(24px,4vw,70px)] bottom-[34px] grid grid-cols-2 items-end gap-y-[18px] border-t border-black/25 pt-6 text-left min-[581px]:grid-cols-[1fr_auto_1fr]"><div className="text-[22px] font-[950] tracking-[-.05em]">NUBE<sup className="ml-0.5 align-top text-[8px]">®</sup><span className="mt-1 block text-[7px] tracking-[.25em]">PÔLE CRÉATION</span></div><div className="row-start-2 flex gap-[26px] text-[8px] font-black tracking-[.15em] min-[581px]:row-auto"><a href="/">FESTIVAL ↗</a><a href="#top">INSTAGRAM ↗</a></div><div className="row-start-2 justify-self-end text-right text-[7px] leading-[1.7] tracking-[.15em] min-[581px]:row-auto">LAUSANNE, CH<br />© 2026 NUBE STUDIO</div></footer>
      </section>
    </main>
  );
}
